// Pravin Mark Jayasinghe
// 5/10/2023
// index.js
// This is the home page for SociaLens.
// It is a simple page that has links to the login, learn, and docs pages.

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// Import the Inter font with the "latin" subset
const inter = Inter({ subsets: ["latin"] });

// Define the Home component
export default function Home() {
  return (
    <>
      <Head>
        <title>SociaLens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* Description section */}
        <div className={styles.description}>
          <p>
            Made with <span className="text-danger">❤️</span> in Hawthorn,
            Melbourne
          </p>
          <div>COS60011</div>
        </div>

        {/* Logo section */}
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/socialens_mono.png"
            alt="Next.js Logo"
            width={500}
            height={120}
            priority
          />
        </div>

        {/* Grid section */}
        <div className={styles.grid}>
          {/* Login card */}
          <a href="/login" className={styles.cardlog}>
            <h2 className="text-danger">
              Login <span>-&gt;</span>
            </h2>
            <p className="text-danger">
              Login to SociaLens and start analyzing social network data.
            </p>
          </a>

          {/* Register card */}
          <a href="/register" className={styles.cardreg}>
            <h2 className="text-warning">
              Register <span>-&gt;</span>
            </h2>
            <p className="text-warning">
              Register an account to use SociaLens.
            </p>
          </a>

          {/* Learn card */}
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>Learn about social network analysis theory.</p>
          </a>

          {/* Docs card */}
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>Learn how to use SociaLens and how it was created. </p>
          </a>
        </div>
      </main>
    </>
  );
}
